#ifndef _CONV_TILE_GEMM_F3S1_PARAMS_H
#define _CONV_TILE_GEMM_F3S1_PARAMS_H

#define CONV_TG_REG_M_SIZE 8
#define CONV_TG_REG_N_SIZE 12

#define CONV_TG_F3_CHN_SIZE 32

#define CONV_TG_F3ST1_DST_SIZE (CONV_TG_REG_N_SIZE)
#define CONV_TG_F3ST1_SRC_SIZE ((CONV_TG_F3ST1_DST_SIZE) + 3 - 1)

#define CONV_TG_F3ST1_M_SIZE (18 * (CONV_TG_REG_M_SIZE))
#define CONV_TG_F3ST1_N_SIZE ((CONV_TG_REG_N_SIZE) * (CONV_TG_REG_N_SIZE))
#define CONV_TG_F3ST1_K_SIZE ((CONV_TG_F3_CHN_SIZE) * 3 * 3)

#endif

