#ifndef _CONV_WINOGRAD_B2F3S1_PARAMS_M1_H
#define _CONV_WINOGRAD_B2F3S1_PARAMS_M1_H

#define CONV_WG_REG_M_SIZE 8
#define CONV_WG_REG_N_SIZE 12

#define CONV_WG_TRANS_SIZE (CONV_WG_REG_N_SIZE)
#define CONV_WG_DST_PAD_SIZE ((CONV_WG_TRANS_SIZE) * 2)
#define CONV_WG_SRC_PAD_SIZE ((CONV_WG_DST_PAD_SIZE) + 3 - 1)

#define CONV_WGB2_F3S1_M_SIZE (18 * (CONV_WG_REG_M_SIZE))
#define CONV_WGB2_F3S1_N_SIZE ((CONV_WG_REG_N_SIZE) * (CONV_WG_REG_N_SIZE))
#define CONV_WGB2_F3S1_K_SIZE 384

#endif

